import streamlit as st
import datetime
import requests
import sys

BASE_URL = "http://localhost:8000"

st.set_page_config()

st.title("AI Trip Planner")



if "messages" not in st.session_state:
    st.session_state.messages = []
    
st.header("How can I help you in planning a trip? Let me know where do you wnat to visit.")

with st.form(key="query_form",clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        ## Show user message
        # show thinging spinner while backend process
        with st.spinner('Bot is thinking....'):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)
            
        if response.status_code == 200:
            answer = response.json().get("answer","No answer returned")
            markdown_content = f"""# AI Travel Plan
            
            # **Generated:** {datetime.datetime.now().strftime("%Y-%m-%d at %H:%M")}
            # **Created by:** Travel Agent
            
            ---
            
            {answer}
            
            ---
            
            * This travel plan was generated by AI. Please verify all information, especially prices 
            """
            st.markdown(markdown_content)
        else:
            st.error(" Bot failed to respond: " + response.text)
    except Exception as e : 
        raise f"This response failed due to {e}" 